### ISSUE TITLE
Calibration 

### ISSUE THREAD

**Issue by prolley-parnell** [FlorentLM/mokap#1]
Hi Flo, I'm having issues with attempting to calibrate the cameras:
All 5 cameras are connected and can successfully collect frames and save them.
Here is the error print out:

```python traceback
Exception in thread Exception in thread Thread-3 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Thread-5 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-4 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
    self.run()
    self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    image_with_vis = self._update_visualisations()
  File "/home/persie/mokap/mokap/interface.py", line 960, in _update_visualisations
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    h, w = self.videofeed_shape
    image_with_vis = self._update_visualisations()
  File "/home/persie/mokap/mokap/interface.py", line 960, in _update_visualisations
  File "/home/persie/mokap/mokap/interface.py", line 250, in videofeed_shape
    image_with_vis = self._update_visualisations()
    h, w = self.VIDEO_PANEL.winfo_height(), self.VIDEO_PANEL.winfo_width()
  File "/home/persie/mokap/mokap/interface.py", line 960, in _update_visualisations
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/tkinter/__init__.py", line 1127, in winfo_height
    h, w = self.videofeed_shape
  File "/home/persie/mokap/mokap/interface.py", line 250, in videofeed_shape
    self.tk.call('winfo', 'height', self._w))
_tkinter.    h, w = self.videofeed_shape
TclError: bad window path name ".!toplevel3.!panedwindow.!label"  File "/home/persie/mokap/mokap/interface.py", line 250, in videofeed_shape

    h, w = self.VIDEO_PANEL.winfo_height(), self.VIDEO_PANEL.winfo_width()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/tkinter/__init__.py", line 1127, in winfo_height
    h, w = self.VIDEO_PANEL.winfo_height(), self.VIDEO_PANEL.winfo_width()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/tkinter/__init__.py", line 1127, in winfo_height
    self.tk.call('winfo', 'height', self._w))
_tkinter.TclError: bad window path name ".!toplevel.!panedwindow.!label"
    self.tk.call('winfo', 'height', self._w))
_tkinter.TclError: bad window path name ".!toplevel2.!panedwindow.!label"
Exception in thread Thread-11 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    image_with_vis = self._update_visualisations()
  File "/home/persie/mokap/mokap/interface.py", line 707, in _update_visualisations
    image = self._full_frame_processing()
  File "/home/persie/mokap/mokap/interface.py", line 690, in _full_frame_processing
    return self._detect()
  File "/home/persie/mokap/mokap/interface.py", line 523, in _detect
    marker_corners, marker_ids, rejected, recovered = cv2.aruco.refineDetectedMarkers(
AttributeError: module 'cv2.aruco' has no attribute 'refineDetectedMarkers'. Did you mean: 'drawDetectedMarkers'?
Exception in thread Thread-9 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    Exception in thread Thread-12 (update)self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
:
Exception in thread Thread-8 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-10 (update):
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    image_with_vis = self._update_visualisations()
  File "/home/persie/mokap/mokap/interface.py", line 707, in _update_visualisations
    self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
    image = self._full_frame_processing()    self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run

  File "/home/persie/mokap/mokap/interface.py", line 690, in _full_frame_processing
    self.run()
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    image_with_vis = self._update_visualisations()
  File "/home/persie/mokap/mokap/interface.py", line 707, in _update_visualisations
    self._target(*self._args, **self._kwargs)
    return self._detect()
  File "/home/persie/mokap/mokap/interface.py", line 523, in _detect
    image = self._full_frame_processing()
  File "/home/persie/mokap/mokap/interface.py", line 690, in _full_frame_processing
    return self._detect()  File "/home/persie/mokap/mokap/interface.py", line 410, in update

  File "/home/persie/mokap/mokap/interface.py", line 523, in _detect
    self._target(*self._args, **self._kwargs)
  File "/home/persie/mokap/mokap/interface.py", line 410, in update
    marker_corners, marker_ids, rejected, recovered = cv2.aruco.refineDetectedMarkers(
AttributeError: module 'cv2.aruco' has no attribute 'refineDetectedMarkers'    marker_corners, marker_ids, rejected, recovered = cv2.aruco.refineDetectedMarkers(. Did you mean: 'drawDetectedMarkers'?

    image_with_vis = self._update_visualisations()AttributeError: 
  File "/home/persie/mokap/mokap/interface.py", line 707, in _update_visualisations
    image_with_vis = self._update_visualisations()
  File "/home/persie/mokap/mokap/interface.py", line 707, in _update_visualisations
module 'cv2.aruco' has no attribute 'refineDetectedMarkers'. Did you mean: 'drawDetectedMarkers'?
    image = self._full_frame_processing()    image = self._full_frame_processing()
  File "/home/persie/mokap/mokap/interface.py", line 690, in _full_frame_processing

  File "/home/persie/mokap/mokap/interface.py", line 690, in _full_frame_processing
    return self._detect()
  File "/home/persie/mokap/mokap/interface.py", line 523, in _detect
    return self._detect()
  File "/home/persie/mokap/mokap/interface.py", line 523, in _detect
    marker_corners, marker_ids, rejected, recovered = cv2.aruco.refineDetectedMarkers(
AttributeError: module 'cv2.aruco' has no attribute 'refineDetectedMarkers'. Did you mean: 'drawDetectedMarkers'?
    marker_corners, marker_ids, rejected, recovered = cv2.aruco.refineDetectedMarkers(
AttributeError: module 'cv2.aruco' has no attribute 'refineDetectedMarkers'. Did you mean: 'drawDetectedMarkers'?
```

And if I click "Aquisition", this is also printed out.

```python traceback
[INFO] Trigger started at 200 Hz
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/persie/miniconda3/envs/mokap/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/persie/mokap/mokap/interface.py", line 1567, in _toggle_acquisition
    w.camera_controls_sliders['framerate'].config(state='disabled', troughcolor=self.col_lightgray)
AttributeError: 'VideoWindowCalib' object has no attribute 'camera_controls_sliders'
[INFO] Grabbing started with 5 cameras...
```

**Comment by FlorentLM** [comment]
This is an OpenCV version incompatibility, it needs opencv-contrib-python version 4+, but the updated `environment.yml` file should take care of this :)
